<?php

/**
 * mdUnit
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    mdShoppingPlugin
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginmdUnit extends BasemdUnit
{
/**
	 * Returns the coefficient that connects this unit with $drUnit
	 * Comparations:
	 * $this = $drUnit => 1
	 * $this converted to $drUnit => ratio
	 * $drUnit converted to $this => 1/ratio
	 *
	 * @param drUnit $drUnit
	 * @return double
	 * @author maui Propel || Rodrigo Santellan Doctrine
	 **/
	public function getRatioWith($mdUnit)
	{
		if ($this == $mdUnit)
			return 1;
		else{

			$convertion = Doctrine::getTable('mdUnitConvertion')->getRatio($this->getId (),$mdUnit->getId ());

			if ($convertion == null ){

				$convertion = Doctrine::getTable('mdUnitConvertion')->getRatio($mdUnit->getId (),$this->getId ());
				return 1/$convertion->getRatio();

			}
			return $convertion->getRatio();
		}
	}

    public function getObjectClass()
    {
        return get_class($this);
    }
}