<?php

/**
 * mdProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    naturalia
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class mdProduct extends PluginmdProduct
{
    
    public function retrieveDefault() {
        return "/images/noImage.jpg";
    }

  public function postSave($event) 
  {
    $culture = sfContext::getInstance()->getUser()->getCulture();
    $mdProductSearch = Doctrine::getTable("mdProductSearch")->find($this->getId());
    if(!$mdProductSearch)
    {
      $mdProductSearch = new mdProductSearch();
      $mdProductSearch->setId($this->getId());
    }
    
    $mdProductSearch->setName($this->getName());
    $mdProductSearch->setIsPublic($this->getIsPublic());
    $mdProductSearch->setPrice($this->getPrice());
    $mdProductSearch->save();
  }
}
