<?php

/**
 * MdSaleableRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MdSaleableRelationTable extends PluginMdSaleableRelationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MdSaleableRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MdSaleableRelation');
    }
}