<?php

/**
 * mdUnitConvertionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdUnitConvertionTable extends PluginmdUnitConvertionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdUnitConvertionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdUnitConvertion');
    }
}