<?php

/**
 * BasemdCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $label
 * @property string $name
 * @property string $object_class_name
 * @property integer $md_category_parent_id
 * @property integer $priority
 * @property mdCategory $mdCategory
 * @property Doctrine_Collection $mdCategoryObject
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getLabel()                 Returns the current record's "label" value
 * @method string              getName()                  Returns the current record's "name" value
 * @method string              getObjectClassName()       Returns the current record's "object_class_name" value
 * @method integer             getMdCategoryParentId()    Returns the current record's "md_category_parent_id" value
 * @method integer             getPriority()              Returns the current record's "priority" value
 * @method mdCategory          getMdCategory()            Returns the current record's "mdCategory" value
 * @method Doctrine_Collection getMdCategoryObject()      Returns the current record's "mdCategoryObject" collection
 * @method mdCategory          setId()                    Sets the current record's "id" value
 * @method mdCategory          setLabel()                 Sets the current record's "label" value
 * @method mdCategory          setName()                  Sets the current record's "name" value
 * @method mdCategory          setObjectClassName()       Sets the current record's "object_class_name" value
 * @method mdCategory          setMdCategoryParentId()    Sets the current record's "md_category_parent_id" value
 * @method mdCategory          setPriority()              Sets the current record's "priority" value
 * @method mdCategory          setMdCategory()            Sets the current record's "mdCategory" value
 * @method mdCategory          setMdCategoryObject()      Sets the current record's "mdCategoryObject" collection
 * 
 * @package    naturalia
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_category');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('label', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('object_class_name', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('md_category_parent_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('priority', 'integer', 2, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('mdCategory', array(
             'local' => 'md_category_parent_id',
             'foreign' => 'id'));

        $this->hasMany('mdCategoryObject', array(
             'local' => 'id',
             'foreign' => 'md_category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $mdi18nbehavior0 = new mdI18nBehavior();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'uniqueBy' => 
             array(
              0 => 'lang',
              1 => 'name',
              2 => 'id',
             ),
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($timestampable0);
        $this->actAs($mdi18nbehavior0);
        $this->actAs($i18n0);
    }
}