<?php

/**
 * BasemdCategoryObject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $object_id
 * @property integer $md_category_id
 * @property string $object_class_name
 * @property integer $priority
 * @property mdCategory $mdCategory
 * 
 * @method integer          getObjectId()          Returns the current record's "object_id" value
 * @method integer          getMdCategoryId()      Returns the current record's "md_category_id" value
 * @method string           getObjectClassName()   Returns the current record's "object_class_name" value
 * @method integer          getPriority()          Returns the current record's "priority" value
 * @method mdCategory       getMdCategory()        Returns the current record's "mdCategory" value
 * @method mdCategoryObject setObjectId()          Sets the current record's "object_id" value
 * @method mdCategoryObject setMdCategoryId()      Sets the current record's "md_category_id" value
 * @method mdCategoryObject setObjectClassName()   Sets the current record's "object_class_name" value
 * @method mdCategoryObject setPriority()          Sets the current record's "priority" value
 * @method mdCategoryObject setMdCategory()        Sets the current record's "mdCategory" value
 * 
 * @package    naturalia
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdCategoryObject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_category_object');
        $this->hasColumn('object_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('md_category_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('object_class_name', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('priority', 'integer', 2, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 2,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('mdCategory', array(
             'local' => 'md_category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}