<?php

/**
 * PluginmdProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginmdProfile extends BasemdProfile
{

	public function getObjectClass(){
		return get_class($this);
	}

    public function preSave($event)
    {
        //sfContext::getInstance()->getLogger()->log('mdDynamicContent - preSave, refrescamos el cache');
        Doctrine::getTable('mdProfile')->refreshCache($this->getId());
    }

    public function postDelete($event)
    {
        //sfContext::getInstance()->getLogger()->log('mdDynamicContent - postDelete, refrescamos el cache');
        Doctrine::getTable('mdProfile')->refreshCache($this->getId());
    }

}