<?php

/**
 * mdProductSearchTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdProductSearchTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdProductSearchTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdProductSearch');
    }

    public function retrieveOneByIdAndLang($productId, $lang)
    {
      $query = $this->createQuery("mdPS");
      $query->addWhere("mdPS.id = ?", $productId)
            ->addWhere("mdPS.lang = ?", $lang);
      return $query->fetchOne();
    }
    
    public function retrieveSearchQuery($phrase = "", $order = 0)
    {
      $query = $this->createQuery("mdPS");
      //$query->select("mdPS.md_user_id");
      $pieces = explode(" ", $phrase);
      $count = 0;

      foreach($pieces as $word)
      {
        if(strlen($word) > 1)
        {
          $count++;
          $query->orWhere("mdPS.name LIKE ? OR mdPS.descripcion LIKE ? OR mdPS.premios LIKE ? OR mdPS.presentaciones LIKE ? OR mdPS.consistencia LIKE ? OR mdPS.textura LIKE ?", array("%".$word."%", "%".$word."%", "%".$word."%", "%".$word."%", "%".$word."%", "%".$word."%"));
        }
      }
      
      if($count == 0)
      {
        $query->addWhere("mdPS.id = ?", 0);
      }
      $query->addWhere("mdPS.is_public = ?", true);
      switch($order)
      {
        
        default:
          $query->orderBy("mdPS.id ASC");
          break;
      }
      
      //$query->setHydrationMode(Doctrine_Core::HYDRATE_NONE);
      return $query;
    }
}
