<?php

/**
 * mdUnitConvertion
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    mdShoppingPlugin
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginmdUnitConvertion extends BasemdUnitConvertion
{
}