<?php

/**
 * PluginmdCurrencyConvertion
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginmdCurrencyConvertion extends BasemdCurrencyConvertion
{

    public static function convert($currencyFrom, $currencyTo, $value)
    {

        if($currencyFrom === $currencyTo)
        {

            return $value;

        }else
        { //Aplico conversion

            $mdCurrencyConvertion = Doctrine::getTable('mdCurrencyConvertion')->findCurrencyConvertion($currencyFrom, $currencyTo);
            return ($value * $mdCurrencyConvertion->getRatio());

        }

    }

}