<?php

/**
 * mdCurrencyConvertionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdCurrencyConvertionTable extends PluginmdCurrencyConvertionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdCurrencyConvertionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdCurrencyConvertion');
    }
}