<?php

/**
 * mdCurrencyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdCurrencyTable extends PluginmdCurrencyTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdCurrencyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdCurrency');
    }
}