<?php

/**
 * mdProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdProductTable extends PluginmdProductTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdProduct');
    }
}