<?php

/**
 * mdAttributeValue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mdAttributePlugin
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginmdAttributeValue extends BasemdAttributeValue
{
  public static function retrieveValueList($mdAttributeId)
  {
    $list = Doctrine::getTable('mdAttributeValue')->find($mdAttributeId);
    $return = array();
    foreach($list as $obj)
    {
      $retun[$obj->getId()] = $obj->getName();
    }
    return $return;
  }
}
