_categoriasMenu:
  enabled:     false
  lifetime:    21600

_productoSmallInfo:
  enabled:     false
  lifetime:    21600

_productoBigInfo:
  enabled:     false
  lifetime:    21600

_productoBusqueda:
  enabled:     false
  lifetime:    21600
  
_categoriaIndexInfo:
  enabled:     false
  lifetime:    21600
