<?php

/**
 * BasemdUnit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $symbol
 * @property Doctrine_Collection $mdUnitConvertion
 * @property Doctrine_Collection $mdProduct
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getName()             Returns the current record's "name" value
 * @method string              getSymbol()           Returns the current record's "symbol" value
 * @method Doctrine_Collection getMdUnitConvertion() Returns the current record's "mdUnitConvertion" collection
 * @method Doctrine_Collection getMdProduct()        Returns the current record's "mdProduct" collection
 * @method mdUnit              setId()               Sets the current record's "id" value
 * @method mdUnit              setName()             Sets the current record's "name" value
 * @method mdUnit              setSymbol()           Sets the current record's "symbol" value
 * @method mdUnit              setMdUnitConvertion() Sets the current record's "mdUnitConvertion" collection
 * @method mdUnit              setMdProduct()        Sets the current record's "mdProduct" collection
 * 
 * @package    naturalia
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdUnit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_unit');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('symbol', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('mdUnitConvertion', array(
             'local' => 'id',
             'foreign' => 'from_unit'));

        $this->hasMany('mdProduct', array(
             'local' => 'id',
             'foreign' => 'md_unit_id'));

        $mdi18nbehavior0 = new mdI18nBehavior();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($mdi18nbehavior0);
        $this->actAs($i18n0);
    }
}