<?php

/**
 * BasemdCurrency
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $code
 * @property string $symbol
 * @property Doctrine_Collection $mdCurrencyConvertion
 * @property Doctrine_Collection $mdProduct
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method string              getName()                 Returns the current record's "name" value
 * @method string              getCode()                 Returns the current record's "code" value
 * @method string              getSymbol()               Returns the current record's "symbol" value
 * @method Doctrine_Collection getMdCurrencyConvertion() Returns the current record's "mdCurrencyConvertion" collection
 * @method Doctrine_Collection getMdProduct()            Returns the current record's "mdProduct" collection
 * @method mdCurrency          setId()                   Sets the current record's "id" value
 * @method mdCurrency          setName()                 Sets the current record's "name" value
 * @method mdCurrency          setCode()                 Sets the current record's "code" value
 * @method mdCurrency          setSymbol()               Sets the current record's "symbol" value
 * @method mdCurrency          setMdCurrencyConvertion() Sets the current record's "mdCurrencyConvertion" collection
 * @method mdCurrency          setMdProduct()            Sets the current record's "mdProduct" collection
 * 
 * @package    naturalia
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdCurrency extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_currency');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('code', 'string', 16, array(
             'type' => 'string',
             'unique' => true,
             'length' => 16,
             ));
        $this->hasColumn('symbol', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('mdCurrencyConvertion', array(
             'local' => 'id',
             'foreign' => 'currency_from'));

        $this->hasMany('mdProduct', array(
             'local' => 'id',
             'foreign' => 'md_currency_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $mdi18nbehavior0 = new mdI18nBehavior();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($mdi18nbehavior0);
        $this->actAs($i18n0);
    }
}