<?php

/**
 * mdAttributeValueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdAttributeValueTable extends PluginmdAttributeValueTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdAttributeValueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdAttributeValue');
    }
}