<?php

/**
 * mdProfileObjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdProfileObjectTable extends PluginmdProfileObjectTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdProfileObjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdProfileObject');
    }
}