<?php

/**
 * mdAttributeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdAttributeTable extends PluginmdAttributeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdAttributeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdAttribute');
    }
}