<?php

/**
 * mdAttributeObjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdAttributeObjectTable extends PluginmdAttributeObjectTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdAttributeObjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdAttributeObject');
    }
}