<?php

/**
 * mdProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdProfileTable extends PluginmdProfileTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdProfile');
    }
}