<?php

/**
 * mdProfileAttributeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdProfileAttributeTable extends PluginmdProfileAttributeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdProfileAttributeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdProfileAttribute');
    }
}