<?php

/**
 * PluginmdCategoryObject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginmdCategoryObject extends BasemdCategoryObject
{
  public function retrieveObject(){
		return Doctrine::getTable ( $this->getMdCategory()->getObjectClassName() )->find($this->getObjectId());
	}

    public function preSave($event)
  {
      Doctrine::getTable('mdCategory')->refreshCacheByObject($this->getObjectId(), $this->getObjectClassName());

  }

  public function postDelete($event)
  {
    Doctrine::getTable('mdCategory')->refreshCacheByObject($this->getObjectId(), $this->getObjectClassName());
  }
      
}
