<?php if( sfConfig::get( 'sf_plugins_auth_first_login', false ) ):

/**
 * PluginmdFirstAccess
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginmdFirstAccess extends BasemdFirstAccess
{

}

endif;