<?php

/**
 * BasemdDynamicContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $publish_at
 * @property timestamp $publish_up_to
 * @property string $type_name
 * @property integer $priority
 * @property boolean $is_public
 * 
 * @method integer          getId()            Returns the current record's "id" value
 * @method timestamp        getPublishAt()     Returns the current record's "publish_at" value
 * @method timestamp        getPublishUpTo()   Returns the current record's "publish_up_to" value
 * @method string           getTypeName()      Returns the current record's "type_name" value
 * @method integer          getPriority()      Returns the current record's "priority" value
 * @method boolean          getIsPublic()      Returns the current record's "is_public" value
 * @method mdDynamicContent setId()            Sets the current record's "id" value
 * @method mdDynamicContent setPublishAt()     Sets the current record's "publish_at" value
 * @method mdDynamicContent setPublishUpTo()   Sets the current record's "publish_up_to" value
 * @method mdDynamicContent setTypeName()      Sets the current record's "type_name" value
 * @method mdDynamicContent setPriority()      Sets the current record's "priority" value
 * @method mdDynamicContent setIsPublic()      Sets the current record's "is_public" value
 * 
 * @package    naturalia
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdDynamicContent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_dynamic_content');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('publish_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('publish_up_to', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('type_name', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'dinamico',
             'length' => 128,
             ));
        $this->hasColumn('priority', 'integer', 2, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 2,
             ));
        $this->hasColumn('is_public', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $mdcontentbehavior0 = new mdContentBehavior();
        $mdattributebehavior0 = new mdAttributeBehavior();
        $mdmediabehavior0 = new mdMediaBehavior();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($mdcontentbehavior0);
        $this->actAs($mdattributebehavior0);
        $this->actAs($mdmediabehavior0);
        $this->actAs($timestampable0);
    }
}