<?php

/**
 * BasemdProfileObject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $object_id
 * @property string $object_class_name
 * @property integer $md_profile_id
 * @property boolean $active
 * @property mdProfile $mdProfile
 * 
 * @method integer         getId()                Returns the current record's "id" value
 * @method integer         getObjectId()          Returns the current record's "object_id" value
 * @method string          getObjectClassName()   Returns the current record's "object_class_name" value
 * @method integer         getMdProfileId()       Returns the current record's "md_profile_id" value
 * @method boolean         getActive()            Returns the current record's "active" value
 * @method mdProfile       getMdProfile()         Returns the current record's "mdProfile" value
 * @method mdProfileObject setId()                Sets the current record's "id" value
 * @method mdProfileObject setObjectId()          Sets the current record's "object_id" value
 * @method mdProfileObject setObjectClassName()   Sets the current record's "object_class_name" value
 * @method mdProfileObject setMdProfileId()       Sets the current record's "md_profile_id" value
 * @method mdProfileObject setActive()            Sets the current record's "active" value
 * @method mdProfileObject setMdProfile()         Sets the current record's "mdProfile" value
 * 
 * @package    naturalia
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdProfileObject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_profile_object');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('object_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('object_class_name', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('md_profile_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('mdProfile', array(
             'local' => 'md_profile_id',
             'foreign' => 'id'));
    }
}