<?php

/**
 * BasemdAttributeObject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $object_id
 * @property string $object_class_name
 * @property int $md_attribute_id
 * @property int $md_attribute_value_id
 * @property text $value_non_translated
 * @property string $value
 * @property int $md_profile_id
 * @property mdAttribute $mdAttribute
 * @property mdAttributeValue $mdAttributeValue
 * @property mdProfile $mdProfile
 * 
 * @method integer           getId()                    Returns the current record's "id" value
 * @method integer           getObjectId()              Returns the current record's "object_id" value
 * @method string            getObjectClassName()       Returns the current record's "object_class_name" value
 * @method int               getMdAttributeId()         Returns the current record's "md_attribute_id" value
 * @method int               getMdAttributeValueId()    Returns the current record's "md_attribute_value_id" value
 * @method text              getValueNonTranslated()    Returns the current record's "value_non_translated" value
 * @method string            getValue()                 Returns the current record's "value" value
 * @method int               getMdProfileId()           Returns the current record's "md_profile_id" value
 * @method mdAttribute       getMdAttribute()           Returns the current record's "mdAttribute" value
 * @method mdAttributeValue  getMdAttributeValue()      Returns the current record's "mdAttributeValue" value
 * @method mdProfile         getMdProfile()             Returns the current record's "mdProfile" value
 * @method mdAttributeObject setId()                    Sets the current record's "id" value
 * @method mdAttributeObject setObjectId()              Sets the current record's "object_id" value
 * @method mdAttributeObject setObjectClassName()       Sets the current record's "object_class_name" value
 * @method mdAttributeObject setMdAttributeId()         Sets the current record's "md_attribute_id" value
 * @method mdAttributeObject setMdAttributeValueId()    Sets the current record's "md_attribute_value_id" value
 * @method mdAttributeObject setValueNonTranslated()    Sets the current record's "value_non_translated" value
 * @method mdAttributeObject setValue()                 Sets the current record's "value" value
 * @method mdAttributeObject setMdProfileId()           Sets the current record's "md_profile_id" value
 * @method mdAttributeObject setMdAttribute()           Sets the current record's "mdAttribute" value
 * @method mdAttributeObject setMdAttributeValue()      Sets the current record's "mdAttributeValue" value
 * @method mdAttributeObject setMdProfile()             Sets the current record's "mdProfile" value
 * 
 * @package    naturalia
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdAttributeObject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_attribute_object');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('object_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('object_class_name', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('md_attribute_id', 'int', 4, array(
             'type' => 'int',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('md_attribute_value_id', 'int', 4, array(
             'type' => 'int',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('value_non_translated', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('value', 'string', 1024, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1024,
             ));
        $this->hasColumn('md_profile_id', 'int', 4, array(
             'type' => 'int',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('mdAttribute', array(
             'local' => 'md_attribute_id',
             'foreign' => 'id'));

        $this->hasOne('mdAttributeValue', array(
             'local' => 'md_attribute_value_id',
             'foreign' => 'id'));

        $this->hasOne('mdProfile', array(
             'local' => 'md_profile_id',
             'foreign' => 'id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'value',
             ),
             ));
        $this->actAs($i18n0);
    }
}