<?php

/**
 * BasemdProfileAttribute
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $md_attribute_id
 * @property integer $md_profile_id
 * @property mdAttribute $mdAttribute
 * @property mdProfile $mdProfile
 * 
 * @method integer            getMdAttributeId()   Returns the current record's "md_attribute_id" value
 * @method integer            getMdProfileId()     Returns the current record's "md_profile_id" value
 * @method mdAttribute        getMdAttribute()     Returns the current record's "mdAttribute" value
 * @method mdProfile          getMdProfile()       Returns the current record's "mdProfile" value
 * @method mdProfileAttribute setMdAttributeId()   Sets the current record's "md_attribute_id" value
 * @method mdProfileAttribute setMdProfileId()     Sets the current record's "md_profile_id" value
 * @method mdProfileAttribute setMdAttribute()     Sets the current record's "mdAttribute" value
 * @method mdProfileAttribute setMdProfile()       Sets the current record's "mdProfile" value
 * 
 * @package    naturalia
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdProfileAttribute extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_profile_attribute');
        $this->hasColumn('md_attribute_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('md_profile_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('mdAttribute', array(
             'local' => 'md_attribute_id',
             'foreign' => 'id'));

        $this->hasOne('mdProfile', array(
             'local' => 'md_profile_id',
             'foreign' => 'id'));
    }
}