<?php

/**
 * mdCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdCategoryTable extends PluginmdCategoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdCategory');
    }
}