all:
  .mail:
    php_mailer_enabled: true
    
  Metas:
    prefix: 'Meta_'
    tags: ['title','description','keywords']
    sources:
      title: 'Titulo'
      description: 'Desripcion'
      keywords: 'Keywords'
      